version: "3.8"
services:
  discord-booby-trap:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
    