name: Releases

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Build
        run: go build -ldflags="-X 'main.Version=${{ github.head_ref }}.${{ github.sha }}'" -o bin/boobytrap DiscordBoobyTrap/cmd/discordboobytrap

      - name: Check version
        run: bin/boobytrap --version

#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "release.tar.gz,foo/*.txt"
#          bodyFile: "body.md"